### ISSUE TITLE
Excitation waveform datasets

### ISSUE THREAD

**Issue by vineetbansal** [PrincetonUniversity/magnet#17]
The following comment/code suggests that either the `excitations` constant needs changing, or some data is no longer needed.

https://github.com/PrincetonUniversity/magnet/blob/9389071ba849fe9f4ab9d86dbf79710a129f6dda/app/ui_raw.py#L15

The comment about waveform consolidation also suggests we need to revisit the places where the old excitation are used. In any case, this entails changing code after careful consideration.

**Comment by ds9056** [comment]
In "Download Raw Data", Triangular and Trapezoidal data is merged into a single file, which I called Trapezoidal so far, but I could rename it to Triangular-Trapezoidal. Also, we could split the data in two if we think it is best that way. Additionally, Datasheet is not required.
For "Core Loss Database", Datasheet, Sinusoidal Triangular and Trapezoidal are required.
And for "Core Loss Database", there is no need for Datasheet, and the options of Arbitrary and Simulated are also required.

Maybe it is better for have three variables: excitations_db, excitations_predict and excitations_raw, what do you think?
