### ISSUE TITLE
Core loss for sine wave

### ISSUE THREAD

**Issue by vineetbansal** [PrincetonUniversity/magnet#3]
I'm wondering if this is correct:
https://github.com/PrincetonUniversity/Magnet/blob/af49eb1108079c2c2d072d1c3224d0ee1df2c09c/main.py#L323

Should the integral be evaluated from 0 to T, like in the other waveforms (example below):
```
def calc_iGSE_tagl(Freq, Flux, flux_list, duty_list, ki, alpha, beta):
    time = np.linspace(0, 1 / Freq, 10001)
    ...
```

**Comment by minjiechen** [comment]
This is ok. Not a big deal here.
