### ISSUE TITLE
Homepage: csv-export does not work

### ISSUE THREAD

**Issue by gituser789** [PrincetonUniversity/magnet#35]
**Describe the bug**
'Download Raw Data' generates an empty .csv file 

**To Reproduce**
1. Go to ['https://mag-net.princeton.edu/'](https://mag-net.princeton.edu/)
2. Chose a material
3. Download Raw Data
4. The downloaded .csv-file is empty

**Expected behavior**
Downloaded .csv-file contains data

**Comment by ds9056** [comment]
Thank you for the feedback, it should be fixed now.
